package server.protocol_RPC;

public enum RequestType {
  LOGIN,
  LOGOUT,
  INSCRIERE_PARTICIPANT,
  FIND_ACCOUNT_ORGANIZATOR,
  FIND_PARTICIPANT_NUME_PRENUME_VARSTA,
  FIND_ALL_PARTICIPANTS,
  FILTER_PROBA_CATEGORIE_PARTICIPANT,
  FIND_CONCURS_PROBA_CATEGORIE,
  NUMAR_PROBE_PENTRU_PARTICIPANT,
  SAVE_INSCRIERE,
  SAVE_PARTICIPANT,
  SAVE_CONCURS,
  CREATE_AND_SAVE_CONCURS,
  CREATE_AND_SAVE_PARTICIPANT,
  FIND_INSCRIERE_PERS_CONC
}
